// 每次构建前运行：自动 stamp 当前 git hash + 时间戳到 version 文件。
// 用法：npx tsx scripts/stamp-version.ts
import { execSync } from 'child_process';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const ROOT = join(__dirname, '..');
const hash = (() => { try { return execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf8' }).trim(); } catch { return 'unknown'; } })();
const now = new Date().toISOString();
const content = `// Auto-generated by stamp-version.ts — DO NOT HAND-EDIT\nexport const VERSION = '${hash}';\nexport const BUILD_TIME = '${now}';\n`;

const targets = [
  join(ROOT, 'packages', 'core', 'src', 'foundation', 'version.ts'),
  join(ROOT, 'packages', 'bridge', 'src', 'version.ts'),
  join(ROOT, 'packages', 'mcp-server', 'src', 'version.ts'),
];

for (const t of targets) {
  try { mkdirSync(join(t, '..'), { recursive: true }); } catch { /* */ }
  writeFileSync(t, content, 'utf8');
  console.log(`Stamped ${hash} → ${t}`);
}
